# Generated by Django 3.2.18 on 2023-07-04 15:19

from django.db import migrations, models
import users.validators


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0007_auto_20230607_1337'),
        ('users', '0027_alter_botconfig_tg_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='user',
            name='liked_games',
            field=models.ManyToManyField(blank=True, related_name='liked', to='games.Game'),
        ),
        migrations.AlterField(
            model_name='user',
            name='site_collection',
            field=models.ManyToManyField(blank=True, related_name='collected', to='games.Game'),
        ),
        migrations.AlterField(
            model_name='user',
            name='tesera_collection',
            field=models.ManyToManyField(blank=True, related_name='t_collected', to='games.Game'),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(error_messages={'unique': 'Такой пользователь уже существует'}, help_text='Обязательное поле: буквы, цифры, символы: . @ _ -', max_length=150, unique=True, validators=[users.validators.UnicodeUsernameValidator()], verbose_name='username'),
        ),
    ]
